[package]
name = "filterer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.0"
regex = "1"

pest_derive = { version = "2.1.0", optional = true }
pest = { version = "2.1.3", optional = true }

rustyline = { version = "9.0", optional = true }

[features]
default = ["readline"]
pest_parser = ["pest", "pest_derive"]
readline = ["rustyline/default"]

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
